### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ruri-Y** [Tungchaphet/messenger-api.js#4]
**[Improvement]**
Documentation?
using this -> https://readthedocs.org/

**Comment by Tungchaphet** [comment]
Okay let me see :>

**Comment by Tungchaphet** [comment]
@TCO46 =)))

**Comment by TCO46** [comment]
> **[Improvement]** Documentation? using this -> https://readthedocs.org/

Thank you for suggesting that but this document I made is not a complete one. (Sorry for that btw)
