### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by khuepm** [Tungchaphet/messenger-api.js#5]
I got these error when starting the project, please check
```
messenger-api.js/src/client/Utils.js:120
        return () => (defaultValue ??= cb());
                                   ^^^

SyntaxError: Unexpected token '??='
```

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at new Thread (/messenger-api.js/src/structures/Thread.js:27:46)
```

```
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayName' of undefined
    at new Thread (/messenger-api.js/src/structures/Thread.js:34:46)
```

**Comment by Tungchaphet** [comment]
Picture 1: You must update Node.JS to v16 or more to use that operator :>
Picture 2: still in progress :<

**Comment by khuepm** [comment]
Do it need to use the syntax `??=` ?
I mean you can consider for syntax suitable with old Node version.

**Comment by Tungchaphet** [comment]
Yes, because Node.js have some error about import module outsite so we have to use that :<

**Comment by Tungchaphet** [comment]
code 2, 3: sometime facebook return weird object or an update so object have been changed :<
sorry :<
